[package]
name = "bevy_mod_raycast"
version = "0.4.0"
authors = ["Aevyrie <aevyrie@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Ray Casting for the Bevy Engine."
repository = "https://github.com/aevyrie/bevy_mod_raycast/"
keywords = ["gamedev", "graphics", "bevy", "3d", "raycast"]
categories = ["game-engines", "rendering"]
resolver = "2"

[dependencies]
bevy = "0.7.0"

[dev-dependencies]
bevy = "0.7.0"
criterion = "0.3"

[[bench]]
name = "ray_mesh_intersection"
harness = false
